name: AutoRelease

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Wait for other workflows
        run: |
          sleep 300  # 等待5分钟让其他工作流完成

      - name: Download Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            
            // 获取当前仓库的所有workflow runs
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'push',
              status: 'completed',
              created: `>${new Date(Date.now() - 10 * 60 * 1000).toISOString()}`  // 最近10分钟内的运行
            });
            
            console.log(`Found ${runs.data.workflow_runs.length} workflow runs`);
            
            for (const run of runs.data.workflow_runs) {
              console.log(`Checking run ${run.id} with SHA ${run.head_sha}, current SHA: ${context.sha}`);
              
              // 只处理与当前commit相关的runs
              if (run.head_sha === context.sha) {
                console.log(`Processing run ${run.id}`);
                
                try {
                  const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: run.id
                  });
                  
                  console.log(`Found ${artifacts.data.artifacts.length} artifacts in run ${run.id}`);
                  
                  for (const artifact of artifacts.data.artifacts) {
                    console.log(`Downloading artifact: ${artifact.name}`);
                    
                    try {
                      const download = await github.rest.actions.downloadArtifact({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        artifact_id: artifact.id,
                        archive_format: 'zip'
                      });
                      
                      fs.writeFileSync(`${artifact.name}.zip`, Buffer.from(download.data));
                      console.log(`Successfully downloaded ${artifact.name}.zip`);
                    } catch (error) {
                      console.error(`Failed to download artifact ${artifact.name}:`, error.message);
                    }
                  }
                } catch (error) {
                  console.error(`Failed to get artifacts for run ${run.id}:`, error.message);
                }
              }
            }

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          release_name: Release ${{ steps.get_tag.outputs.tag_name }}
          draft: false
          prerelease: false

      - name: Unzip Artifacts
        run: |
          for zip in *.zip
          do
            if [ -f "$zip" ]; then
              echo "Unzipping $zip"
              unzip "$zip" || true
            fi
          done

      - name: Upload Release Assets
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const fs = require('fs');
            const release_id = '${{ steps.create_release.outputs.id }}';
            
            console.log('Looking for files to upload...');
            const files = fs.readdirSync('.');
            
            for (const file of files) {
              if (file.endsWith('.tar.gz') || file.endsWith('.zip') || file.endsWith('.deb') || file.endsWith('.rpm')) {
                console.log(`Uploading ${file} to release`);
                try {
                  await github.rest.repos.uploadReleaseAsset({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    release_id: release_id,
                    name: file,
                    data: fs.readFileSync(file)
                  });
                  console.log(`Successfully uploaded ${file}`);
                } catch (error) {
                  console.error(`Failed to upload ${file}:`, error.message);
                }
              }
            }