name: ROS2:Galactic(20.04)

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:galactic-desktop
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y \
          qtbase5-dev \
          qt5-qmake \
          libqt5svg5-dev \
          qtbase5-dev-tools \
          qtbase5-private-dev \
          qt5* \
          libeigen3-dev \
          libgtest-dev \
          libsdl-image1.2-dev \
          libsdl1.2-dev \
          wget

      - name: Update gtest
        run: |
          wget https://github.com/google/googletest/archive/refs/tags/release-1.12.1.tar.gz \
          && tar -zxvf release-1.12.1.tar.gz \
          && cd googletest-release-1.12.1 \
          && mkdir build \
          && cd build \
          && cmake .. \
          && make -j$(nproc) \
          && make install

      - name: Build
        run: |
          source /opt/ros/galactic/setup.bash \
          && rm -rf build \
          && mkdir build/ \
          && cd build/ \
          && cmake .. -DBUILD_WITH_TEST=OFF \
          && make -j$(nproc) \
          && make install

      - name: Test
        run: |
          source /opt/ros/galactic/setup.bash \
          && cd build \
          && make test

      - name: Package Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cd build/install/bin
          tar -czvf ros_qt5_gui_app_galactic_x86_64.tar.gz ./*

      - name: Upload Artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v3
        with:
          name: ros_qt5_gui_app_galactic_x86_64
          path: build/install/bin/ros_qt5_gui_app_galactic_x86_64.tar.gz
